## Class and Objects

In [ ]:
class student:
    name = None
    age = None
    branch = None
    def get_stud_det(self):
        print("GET NAME")
        self.name = input()
        print("GET AGE")
        self.age = input()
        print("GET BRANCH")
        self.branch = input()
    def put_stud_det(self):
        print('NAME', self.name)
        print('AGE', self.age)
        print('BRANCH', self.branch)

stud1 = student()

In [9]:
stud1.get_stud_det()

GET NAME
RAVI
GET AGE
30
GET BRANCH
IT


In [10]:
stud1.put_stud_det()

NAME RAVI
AGE 30
BRANCH IT


In [14]:
class stud:
    def get_n(self, nm):
        self.name = nm
        print(self.name)
    def show_n(self):
        print(self.name)
s1 = stud()

In [15]:
s1.get_n('Karan')

Karan


In [16]:
s1.show_n()

Karan


In [17]:
class student:
    def __init__(self, n,a,br):
        self.name = n
        self.age = a
        self.branch = br
    def show_det(self):
        print(self.name, self.age, self.branch)
        
s2 = student('Karan', 30, 'IT')

In [18]:
s2.show_det()

Karan 30 IT


In [52]:
class car:
    __maxspeed = 0
    __name = 'Safari'
    model = 'TATA'
    def __init__(self):
        self.__maxspeed = 200
        self.__name = 'Sumo'
    def drive(self):
        print('Drive')
        
c=car()

In [53]:
 c.drive()

Drive


In [47]:
c.__maxspeed = 10
c.__name = 'Kia'

In [54]:
print(c.__maxspeed)
print(c.__name)

AttributeError: 'car' object has no attribute '__maxspeed'

In [55]:
print(c.model)

TATA


In [4]:
a=[[1, 2, 4],[5,6,7]]

In [5]:
a

[[1, 2, 4], [5, 6, 7]]

In [6]:
a[0][0]

1

In [18]:
{'':"goo"}

{'': 'goo'}

### Max of 3 number without using max() function

In [10]:

a = [2,4,1]
def max_of_two(x,y):
    if x>y:
        return x
    return y
def max_of_three(x,y,z):
    return max_of_two(x,max_of_two(y,z))

In [11]:
max_of_three(4,8,1)

8

### Multiply all number in list/tuple/sets

In [12]:
def multiply(number):
    total = 1
    for i in number:
        total *= i
    return total
multiply([1,2,3,4])

24

### Count the Uppercase and lowercase letter in string

In [17]:

d = {'UPPERCASE':0, "LOWERCASE":0}
def count_u_l(s):
    for c in s:
        if c.isupper():
            d['UPPERCASE'] += 1
        elif c.islower():
            d["LOWERCASE"] += 1
        else:
            pass
    print('Uppercase letters in string is :', d['UPPERCASE'])
    print('Lowercase letters in string is :', d['LOWERCASE'])

count_u_l('Hi This is KAArmmn')

Uppercase letters in string is : 5
Lowercase letters in string is : 10


## File Handling

In [22]:
import os
print(os.getcwd())

C:\Users\Lenovo


In [25]:
y = lambda x: x%2==0

In [26]:
y(2)

True

In [29]:
str_list = [1,2,3,4]
r = lambda s: s in str_list
r(5)

False

In [48]:
t1 = (0,)
t2 = ("4",6,)
print(t1 + t2)


(0, '4', 6)


In [47]:
tup1 = (1, 'abc', True,)
tup2 = (4,)
print(tup1+tup2)

(1, 'abc', True, 4)


## Multi-threading and Multi-processing

In [ ]:
## MultiThreading in Class

from threading import Thread 

class Hello(Thread):
    def r(self):
        for i in range(5):
            print("Hello")

class Hi(Thread):
    def r(self):
        for i in range(5):
            print("Hi")

            
t1 = Hello()
t2 = Hi()

t1.start()
t2.start()

t1.join()
t2.join()



In [ ]:
## MultiThreading in methods

import threading
import time
def hello():
    for i in range(5):
        time.sleep(0.1)
        print("Hello")
def hi():
    for i in range(5):
        time.sleep(0.1)
        print("Hi")

t1 = threading.Thread(target=hello, args = ())
t2 = threading.Thread(target=hi, args = ())

t1.start()
t2.start()

t1.join()
t2.join()

print('Done')

In [ ]:
## Multiprocesessing

import multiprocessing
import time
def hello():
    for i in range(5):
        print("Hello")
def hi():
    for i in range(5):
        print("Hi")

t1 = multiprocessing.Process(target=hello, args = ())
# t2 = multiprocessing.Process(target=hi, args = ())

t1.start()
# t2.start()

t1.join()
# t2.join()
print('Done')

## Bubble Sort

In [ ]:
# 5. Sort algo in py
## Bubbule sort --> 2 loops and swap is common 
def bubble_sort(lst):
    for i in range(len(lst)-1, -1, -1):
        for j in range(i):
            # print("j and lst[j]", j,lst[j]) 
            
            if lst[j]>lst[j+1]:  ## lst[0]>lst[1]  6,3
                
#                 temp = lst[j]    ## Swap logic
#                 lst[j]=lst[j+1]
#                 lst[j+1]=temp
                lst[j], lst[j+1] = lst[j+1], lst[j]

lst = [6,3,8,4,1,9,0,2,1]
print(len(lst))
bubble_sort(lst)
print(lst)



## Decorator

In [ ]:
# 4. # create decorator of addintion of 2 num
def decorator_function(display):
    def wrapper_func(*args):
        res = args[0]+args[1]
        display(*args)
        print("Addition is {}".format(res))
    return wrapper_func

@decorator_function
def display(a, b):
    print("Number is {} + {}".format(a, b))

display(3,10)

## Generator

In [ ]:
## 13. Out of sample Ganerator to get multiple of 3

def generator_func(n):
    for i in range(n):
        val = i*3
        if val <=20:
            yield ("Generator values are {}".format(val))
            
g_obj = generator_func(30)

while True:
    try:
        print(next(g_obj))
    except StopIteration:
        break



# Numpy

In [2]:
import numpy as np

In [56]:
a = np.zeros((5,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [59]:
a = np.identity(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
t1 = (1,2,3)
t2 = (4,5,5)

In [62]:
t1+t2

(1, 2, 3, 4, 5, 5)

In [3]:
arr = np.array([[1,2],[2,4],[3,4,[1,3]]])
arr

array([list([1, 2]), list([2, 4]), list([3, 4, [1, 3]])], dtype=object)

In [4]:
arr.ravel()

array([list([1, 2]), list([2, 4]), list([3, 4, [1, 3]])], dtype=object)

In [5]:
arr.flatten()

array([list([1, 2]), list([2, 4]), list([3, 4, [1, 3]])], dtype=object)

In [74]:
for i in arr.flat:
    print(i)

1
2
2
4


In [76]:
for i in np.nditer(arr):
    print(i)

1
2
2
4


In [77]:
arr.shape

(2, 2)

In [79]:
arr.size

4

In [81]:
a = np.arange(1,50,5)

In [84]:
a.argmax()

9

In [86]:
np.where(a%2==0) ## index value

(array([1, 3, 5, 7, 9], dtype=int64),)

In [107]:
d = list(np.where(a%2==0))
d

[array([1, 3, 5, 7, 9], dtype=int64)]

## Pandas

In [2]:
import pandas as pd

In [4]:
arr = [1,2,3,4]
s1 = pd.Series(arr)
print(s1)

0    1
1    2
2    3
3    4
dtype: int64


In [14]:
 import numpy as np
import pandas as pd

In [27]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array is :")
print(arr1)
index = ['a','b','c']
print('Index is:')
print(index)
col = ['c11','c2','c3']
print('column is :')
print(col)

Array is :
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Index is:
['a', 'b', 'c']
column is :
['c11', 'c2', 'c3']


In [28]:
df1 = pd.DataFrame(arr1, index=index, columns=col)
df1

c11  c2  c3
a    1   2   3
b    4   5   6
c    7   8   9

In [30]:
dic = {'c1':[1,2,3],'c2':[2,4,6], 'c3':[1,23,4]}
df2 = pd.DataFrame(dic, index = index)
df2

c1  c2  c3
a   1   2   1
b   2   4  23
c   3   6   4

In [31]:
df1.describe()

c11   c2   c3
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [36]:
df1.sort_values(by='c11')

c11  c2  c3
a    1   2   3
b    4   5   6
c    7   8   9

In [37]:
df1

c11  c2  c3
a    1   2   3
b    4   5   6
c    7   8   9

In [40]:
df1.iloc[1:3]

c11  c2  c3
b    4   5   6
c    7   8   9

In [43]:
df1.loc['b','c11']=4.5
df1

c11  c2  c3
a  1.0   2   3
b  4.5   5   6
c  7.0   8   9